test:
  DOMAIN: 'test'
  MAILER_SENDER: 'test@email.com'
  SECRET_KEY_BASE: 'asdfasdf'
  SECRET_TOKEN: 'asdf'
  SMTP_SERVER: ''
  SMTP_PORT: ''
  SMTP_LOGIN: ''
  SMTP_PASSWORD: ''
  LOAD_MAILER_RECIPIENTS: 'recipient@test.com'